backend:
  name: git-gateway
  branch: main

local_backend: true

media_folder: static/img
public_folder: /img

collections:
  - name: 'portfolio'
    label: 'Nos publications'
    folder: 'content/portfolio'
    format: 'frontmatter'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Image', name: 'image', widget: 'image' }
      - { label: 'Publié par', name: 'author', widget: 'string' }

  - name: 'collectif'
    label: 'Le collectif'
    folder: 'content/collective'
    format: 'frontmatter'
    create: true
    slug: '{{fullName}}'
    editor:
      preview: false
    fields:
      - { label: 'Nom/Prénom', name: 'fullName', widget: 'string' }
      - { label: 'Fonction', name: 'role', widget: 'string' }
      - { label: 'Texte de présentation', name: 'description', widget: 'string' }
      - { label: 'Mail', name: 'email', widget: 'string' }
      - { label: 'Description image', name: 'avatarAlt', widget: 'string' }
      - { label: 'Image de profil', name: 'avatar', widget: 'image' }
