backend:
  name: git-gateway
  branch: main

local_backend: true
locale: 'fr'
media_folder: static/img
public_folder: /img

collections:
  - name: 'portfolio'
    label: 'Nos publications'
    folder: 'content/portfolio'
    format: 'frontmatter'
    label_singular: ' : NOUVELLE PUBLICATION'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Titre', name: 'title', widget: 'string' }
      - { label: 'Date de publication', name: 'date', widget: 'datetime' }
      - { label: 'Contenu', name: 'description', widget: 'text' }
      - { label: 'Photo', name: 'image', widget: 'image' }
      - { label: 'Crédit de la photo', name: 'imageCredit', widget: 'string', required: false }
      - { label: 'Description de la photo', name: 'imageAlt', widget: 'string', required: false }
      - { label: "Lien vers publication d'origine", name: 'source', widget: 'string', required: false }
      - { label: "Nom du site de la publication d'origine", name: 'sourceName', widget: 'string', required: false }
      - { label: "Vidéo youtube", name: 'video', widget: 'string', required: false }
      - { label: "Audio", name: 'audio', widget: 'file', required: false }
      - {
          label: 'Publié par',
          name: 'author',
          widget: 'relation',
          collection: 'collectif',
          search_fields: ['fullName'],
          value_field: 'fullName',
         }
      - {
          label: 'Tags',
          name: 'tag',
          widget: 'relation',
          collection: "tag",
          search_fields: ['tag'],
          value_field: 'tag',
          multiple: true,
         }

  - name: 'collectif'
    label: 'Le collectif'
    folder: 'content/collective'
    format: 'frontmatter'
    label_singular: ' : MEMBRE DU COLLECTIF'
    create: true
    slug: '{{fullName}}'
    editor:
      preview: false
    fields:
      - { label: 'Nom/Prénom', name: 'fullName', widget: 'string' }
      - { label: 'Fonction', name: 'role', widget: 'string' }
      - { label: 'Texte de présentation', name: 'description', widget: 'text' }
      - { label: 'Mail', name: 'email', widget: 'string' }
      - { label: 'Description image', name: 'avatarAlt', widget: 'string' }
      - { label: 'Image de profil', name: 'avatar', widget: 'image' }

  - name: 'tag'
    label: 'Tag'
    folder: 'content/tags'
    widget: 'list'
    slug: '{{slug}}'
    label_singular: ' : TAG'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Tag', name: 'tag', widget: 'string' }

  - name: 'photos'
    label: 'Photos'
    folder: 'content/photos'
    slug: 'photos'
    label_singular: ' : PHOTOS'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Section', name: 'title', widget: 'string' }
      - { label: "Fond de page d'entrée", name: 'homeBackground', widget: 'image' }
      - { label: "Page d'accueil", name: 'home', widget: 'image' }

  - name: 'texts'
    label: 'Textes'
    folder: 'content/texts'
    slug: 'texts'
    label_singular: ' : TEXTES'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Section', name: 'sectionTitle', widget: 'string' }
      - { label: "Présentation sur la page d'entrée", name: 'homeIntroduction', widget: 'text' }
      - label: "Bloques de texte sur page d'accueil"
        name: 'contentBlock'
        widget: 'list'
        max: 3
        fields:
          - { label: 'Titre', name: 'title', widget: 'string' }
          - { label: 'Contenu', name: 'content', widget: 'text' }
